name: CIFuzz
on: push
jobs:
 Fuzzing:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/setup-java@v3
     with:
      distribution: 'temurin' # See 'Supported distributions' for available options
      java-version: '8'
   - name: Build Fuzzers
     id: build
     uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
     with:
       oss-fuzz-project-name: 'tomcat'
       language: jvm
   - name: Run Fuzzers
     uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
     with:
       oss-fuzz-project-name: 'tomcat'
       language: jvm
       fuzz-seconds: 600
   - name: Upload Crash
     uses: actions/upload-artifact@v3
     if: failure() && steps.build.outcome == 'success'
     with:
       name: artifacts
       path: ./out/artifacts
